version: '3.8'
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - ./app/node_modules

  frontend:
    build: ./myblog
    container_name: frontend_c
    ports:
      - '3000:3000'
    volumes:
      - ./myblog:/app
      - ./app/node_modules
    stdin_open: true